// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy5c_QTIkum1HgAyjc5--QaCCYNcHYcFw',
    appId: '1:315464062158:web:9beb3072049caca9126c9f',
    messagingSenderId: '315464062158',
    projectId: 'freelance-app-be58f',
    authDomain: 'freelance-app-be58f.firebaseapp.com',
    storageBucket: 'freelance-app-be58f.firebasestorage.app',
    measurementId: 'G-0GZLDBQFYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0K6vp6UcQV3c46wR-shReAG2lY161YI',
    appId: '1:315464062158:android:3aa391ba61f72fe2126c9f',
    messagingSenderId: '315464062158',
    projectId: 'freelance-app-be58f',
    storageBucket: 'freelance-app-be58f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAyebhc95DDGU9QpKftxnKsUNgJfplvJM',
    appId: '1:315464062158:ios:4f3eb24b294391a4126c9f',
    messagingSenderId: '315464062158',
    projectId: 'freelance-app-be58f',
    storageBucket: 'freelance-app-be58f.firebasestorage.app',
    iosBundleId: 'com.example.saneeaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAyebhc95DDGU9QpKftxnKsUNgJfplvJM',
    appId: '1:315464062158:ios:4f3eb24b294391a4126c9f',
    messagingSenderId: '315464062158',
    projectId: 'freelance-app-be58f',
    storageBucket: 'freelance-app-be58f.firebasestorage.app',
    iosBundleId: 'com.example.saneeaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy5c_QTIkum1HgAyjc5--QaCCYNcHYcFw',
    appId: '1:315464062158:web:8b1fb95eb727f401126c9f',
    messagingSenderId: '315464062158',
    projectId: 'freelance-app-be58f',
    authDomain: 'freelance-app-be58f.firebaseapp.com',
    storageBucket: 'freelance-app-be58f.firebasestorage.app',
    measurementId: 'G-S6XWGBMJ3D',
  );
}
